name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install & Build Backend
        run: |
          cd backend
          npm install
          npm run build

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install & Build Frontend
        run: |
          cd frontend
          pnpm install --no-frozen-lockfile
          pnpm build
